FROM openjdk:17-jdk-alpine
LABEL authors="Revanth Dandu"


COPY target/blog-app-apis-0.0.1-SNAPSHOT.jar blog-app-apis-0.0.1-SNAPSHOT.jar


ENTRYPOINT ["java", "-jar", "blog-app-apis-0.0.1-SNAPSHOT.jar"]